//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdmin
    {
        public byte ID { get; set; }
        public string ProgUser { get; set; }
        public string Pass { get; set; }
    }
}
